apiVersion: 1

datasources:
  
  - name: db-postgres
    type: postgres
    url: db-postgres:5432
    user: grafana_user
    secureJsonData:
      password: 'grafana_password'
    jsonData:
      database: postgres_db
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1303
      timescaledb: false
  
  - name: db-clickhouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: db-clickhouse
      port: 9000
      username: grafana_user
      tlsSkipVerify: false
    secureJsonData:
      password: grafana_password

