name: Docker Image Check

on:
  pull_request:
    branches:
      - master
  # push:
  #   branches:
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yaml build

      - name: Run airflow-init
        run: |
          docker compose -f docker-compose.yaml up airflow-init
          docker compose -f docker-compose.yaml logs airflow-init
        
      - name: Start all services
        run: |
          docker compose -f docker-compose.yaml up -d

      - name: Start healthchecks
        run: |
          declare -a services=(
            "kaboupi-af-webserver"
            "kaboupi-af-scheduler"
            "kaboupi-af-worker"
            "kaboupi-clickhouse"
            "kaboupi-postgres"
            "kaboupi-grafana"
            "kaboupi-nifi"
            "kaboupi-kafka"
          )

          for service in "${services[@]}"; do
            echo "Waiting for $service to be healthy..."
            until [ "$(docker inspect -f '{{.State.Health.Status}}' ${service})" == "healthy" ]; do
              sleep 5
            done
            echo "Service $service is healthy!"
          done

      - name: Clean up
        run: |
          docker compose -f docker-compose.yaml down
